# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'http://git.supconit.com/mobile/emobilespecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'EMSDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EMSDKDemo
#  pod 'EMNavigatorBarModule'
  pod 'EMSDK', :path =>'../'
#  pod 'EMSDK/AppInfo', :path =>'../'
#  pod 'EMSDK/Camera', :path =>'../'
#  pod 'EMSDK/Modal'
#  pod 'EMSDK/All', :path =>'../'
#  pod 'EMSDK/VideoPreviewer'
end

